🌶️ Short Class Python - Hari 1
"Hari Pertama Kerja di Toko Rempah & Bumbu Wangi Nusantara"
Selamat datang lagi! Kelas ini kelanjutan dari Bootcamp Data Analyst kemarin, jadi kita nggak bakal ngulang dasar-dasar Python dan pandas dari nol lagi. Kalau ada yang lupa soal variabel, list, dict, atau dasar DataFrame (head(), info(), describe()), tonton lagi rekaman sesi sebelumnya dulu ya..

Karena ini kelas lanjutan, hari ini kita bakal langsung tancap gas ke teknik-teknik pandas yang lebih dalam, bukan sekadar ngulang yang basic.

📖 Ceritanya begini...
Kamu baru aja diterima kerja part-time sebagai Data Analyst di Toko Rempah & Bumbu Wangi Nusantara, toko rempah dan bumbu dapur di Bandung. Pemiliknya, Teh Rina, udah jualan hampir setahun, baik lewat toko fisik maupun aplikasi pesan-antar.

Teh Rina udah denger kamu jago pandas dari bootcamp kemarin, jadi kali ini dia langsung kasih pertanyaan-pertanyaan yang lebih spesifik dan detail, bukan cuma "berapa total penjualan" doang.

Data transaksinya bisa kamu lihat di sini:

🔗 https://docs.google.com/spreadsheets/d/1hmH7aVkADkHk3Un8rxGYFb4Xail0sWbK/edit?usp=drivesdk&ouid=106485154383908444810&rtpof=true&sd=true

Yuk gas, kita mulai!

1. Kilas Balik Kilat
Super singkat aja ya, karena kalian udah dapat rekamannya:

pd.read_csv() buat load data, df.head() / df.info() / df.describe() buat kenalan awal
df.isnull().sum() dan df.duplicated().sum() buat cek data kosong dan duplikat
df.groupby("kolom")["kolom_lain"].sum() buat ringkasan per kategori

In [4]:
import pandas as pd
import numpy as np

url_data = "https://docs.google.com/spreadsheets/d/1hmH7aVkADkHk3Un8rxGYFb4Xail0sWbK/export?format=csv"
df = pd.read_csv(url_data)
df["sales_date"] = pd.to_datetime(df["sales_date"])
df['distance_km'] = df['distance_km'].str.replace(',', '.').astype(float)
df['discount'] = df['discount'].str.replace(',', '.').astype(float)

print("Data berhasil di-load!")
print("Jumlah baris dan kolom:", df.shape)
df.head()

Data berhasil di-load!
Jumlah baris dan kolom: (10000, 16)

,sales_date,order_id,customer_name,customer_address,product_name,category,unit,price,quantity,order_type,distance_km,discount,total,shipping_fee,total_sales,status
0,2025-07-17,RMP00001,Customer_1198,"Kecamatan Cicalengka, Kabupaten Bandung",Bunga Lawang (Pekak),Rempah Kering & Bumbu Dapur,50 gr,9000,1,Beli di Toko,0.0,0.0,9000,0,9000,completed
1,2025-09-11,RMP00002,Customer_3969,"Kecamatan Gedebage, Kota Bandung",Kencur,Rempah & Sayuran Segar,250 gr,8000,1,Beli di Toko,0.0,0.0,8000,0,8000,completed
2,2025-11-15,RMP00003,Customer_575,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Gule Sapi,Paket Bumbu Instan,1 paket,15000,2,Diantar (Aplikasi Toko),14.2,0.0,30000,25000,55000,completed
3,2025-06-06,RMP00004,Customer_1394,"Kecamatan Cisarua, Kabupaten Bandung Barat",Paket Bumbu Soto Betawi,Paket Bumbu Instan,1 paket,22000,1,Beli di Toko,0.0,0.0,22000,0,22000,completed
4,2025-12-13,RMP00005,Customer_1382,"Kecamatan Sukajadi, Kota Bandung",Paket Bumbu Woku Manado,Paket Bumbu Instan,1 paket,20000,1,Diantar (Aplikasi Toko),1.5,0.0,20000,0,20000,completed

In [5]:
df.discount.unique()

array([0.  , 0.05, 0.1 ])

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   sales_date        10000 non-null  datetime64[us]
 1   order_id          10000 non-null  str
 2   customer_name     10000 non-null  str
 3   customer_address  10000 non-null  str
 4   product_name      10000 non-null  str
 5   category          10000 non-null  str
 6   unit              10000 non-null  str
 7   price             10000 non-null  int64
 8   quantity          10000 non-null  int64
 9   order_type        10000 non-null  str
 10  distance_km       10000 non-null  float64
 11  discount          10000 non-null  float64
 12  total             10000 non-null  int64
 13  shipping_fee      10000 non-null  int64
 14  total_sales       10000 non-null  int64
 15  status            10000 non-null  str
dtypes: datetime64[us](1), float64(2), int64(5), str(8)
memory usage: 1.2 MB

Cek cepat kerapian data
Sebelum lanjut, kita cek dulu sekilas: missing value, duplikat, dan konsistensi teks.

In [7]:
df.customer_address

0             Kecamatan Cicalengka, Kabupaten Bandung
1                    Kecamatan Gedebage, Kota Bandung
2       Kecamatan Padalarang, Kabupaten Bandung Barat
3          Kecamatan Cisarua, Kabupaten Bandung Barat
4                    Kecamatan Sukajadi, Kota Bandung
                            ...
9995          Kecamatan Cicalengka, Kabupaten Bandung
9996            Kecamatan Banjaran, Kabupaten Bandung
9997    Kecamatan Padalarang, Kabupaten Bandung Barat
9998            Kecamatan Cileunyi, Kabupaten Bandung
9999              Kecamatan Astanaanyar, Kota Bandung
Name: customer_address, Length: 10000, dtype: str

In [8]:
df.head(1)

,sales_date,order_id,customer_name,customer_address,product_name,category,unit,price,quantity,order_type,distance_km,discount,total,shipping_fee,total_sales,status
0,2025-07-17,RMP00001,Customer_1198,"Kecamatan Cicalengka, Kabupaten Bandung",Bunga Lawang (Pekak),Rempah Kering & Bumbu Dapur,50 gr,9000,1,Beli di Toko,0.0,0.0,9000,0,9000,completed

In [9]:
sorted(df['category'].unique())

['Paket Bumbu Instan', 'Rempah & Sayuran Segar', 'Rempah Kering & Bumbu Dapur']

In [10]:
print("Missing Value:")
print(df.isnull().sum().sum(), "total sel kosong dalam dataset")
print("Baris Duplikat:", df.duplicated().sum())
print("Kategori unik:", sorted(df['category'].unique()))
print("Order Type unik:", sorted(df['order_type'].unique()))

Missing Value:
0 total sel kosong dalam dataset
Baris Duplikat: 0
Kategori unik: ['Paket Bumbu Instan', 'Rempah & Sayuran Segar', 'Rempah Kering & Bumbu Dapur']
Order Type unik: ['Beli di Toko', 'Diantar (Aplikasi Toko)']

2. DataFrame: Selecting & Transforming Data
2.1 .loc[]: Filter Baris + Pilih Kolom Sekaligus
Kalau di bootcamp kemarin kita udah belajar filter pakai df[df["kolom"] == nilai], sekarang kita kenalan sama .loc[], yang bisa filter baris DAN milih kolom tertentu dalam satu langkah, formatnya df.loc[kondisi, ["kolom1", "kolom2"]].

In [11]:
df[df.total_sales > 150000].head(1)

,sales_date,order_id,customer_name,customer_address,product_name,category,unit,price,quantity,order_type,distance_km,discount,total,shipping_fee,total_sales,status
123,2025-08-02,RMP00124,Customer_1190,"Kecamatan Sukajadi, Kota Bandung",Paket Bumbu Sambal Hijau,Paket Bumbu Instan,1 paket,32000,5,Diantar (Aplikasi Toko),2.2,0.0,160000,9000,169000,completed

In [ ]:
#loc[]: Filter Baris + Pilih Kolom Sekaligus menggunakan nama kolom

big_transac=df.loc[
    df['total_sales'] > 150000, ["order_id", "product_name", "category","total_sales"]
]

print("Jumlah transaksi besar:", len(big_transac))
big_transac.head()

Jumlah transaksi besar: 39

     order_id               product_name            category  total_sales
123  RMP00124   Paket Bumbu Sambal Hijau  Paket Bumbu Instan       169000
145  RMP00146          Paket Bumbu Pecel  Paket Bumbu Instan       165000
364  RMP00365      Paket Bumbu Rica-Rica  Paket Bumbu Instan       160000
617  RMP00618  Paket Bumbu Coto Makassar  Paket Bumbu Instan       153000
626  RMP00627    Paket Bumbu Sate Padang  Paket Bumbu Instan       153000

2.2 .iloc[]: Ambil Baris/Kolom Berdasarkan Posisi
Kalau .loc[] pakai nama kolom dan kondisi, .iloc[] pakai posisi urutan (index angka), mirip cara kamu ambil item dari list.

In [ ]:
#iloc[]: Filter Baris + Pilih Kolom Sekaligus menggunakan index angka

df.iloc[0:10, 0:8]

,sales_date,order_id,customer_name,customer_address,product_name,category,unit,price
0,2025-07-17,RMP00001,Customer_1198,"Kecamatan Cicalengka, Kabupaten Bandung",Bunga Lawang (Pekak),Rempah Kering & Bumbu Dapur,50 gr,9000
1,2025-09-11,RMP00002,Customer_3969,"Kecamatan Gedebage, Kota Bandung",Kencur,Rempah & Sayuran Segar,250 gr,8000
2,2025-11-15,RMP00003,Customer_575,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Gule Sapi,Paket Bumbu Instan,1 paket,15000
3,2025-06-06,RMP00004,Customer_1394,"Kecamatan Cisarua, Kabupaten Bandung Barat",Paket Bumbu Soto Betawi,Paket Bumbu Instan,1 paket,22000
4,2025-12-13,RMP00005,Customer_1382,"Kecamatan Sukajadi, Kota Bandung",Paket Bumbu Woku Manado,Paket Bumbu Instan,1 paket,20000
5,2025-09-09,RMP00006,Customer_1979,"Kecamatan Cibiru, Kota Bandung",Paket Bumbu Kerupuk Sambal,Paket Bumbu Instan,1 paket,28000
6,2025-09-05,RMP00007,Customer_2026,"Kecamatan Majalaya, Kabupaten Bandung",Jahe,Rempah & Sayuran Segar,250 gr,9000
7,2025-02-05,RMP00008,Customer_2360,"Kecamatan Cidadap, Kota Bandung",Cabai Merah Keriting,Rempah & Sayuran Segar,250 gr,15000
8,2025-09-03,RMP00009,Customer_1197,"Kecamatan Bandung Wetan, Kota Bandung",Asam Jawa,Rempah Kering & Bumbu Dapur,100 gr,6000
9,2025-10-25,RMP00010,Customer_1738,"Kecamatan Cicalengka, Kabupaten Bandung",Paket Bumbu Semur Daging,Paket Bumbu Instan,1 paket,28000

In [15]:
df.iloc[0:3,1:5]

,order_id,customer_name,customer_address,product_name
0,RMP00001,Customer_1198,"Kecamatan Cicalengka, Kabupaten Bandung",Bunga Lawang (Pekak)
1,RMP00002,Customer_3969,"Kecamatan Gedebage, Kota Bandung",Kencur
2,RMP00003,Customer_575,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Gule Sapi

In [16]:
df[['order_id','unit','price']]

      order_id     unit  price
0     RMP00001    50 gr   9000
1     RMP00002   250 gr   8000
2     RMP00003  1 paket  15000
3     RMP00004  1 paket  22000
4     RMP00005  1 paket  20000
...        ...      ...    ...
9995  RMP09996  1 paket  17000
9996  RMP09997    50 gr   9000
9997  RMP09998  1 paket  14000
9998  RMP09999  1 paket  32000
9999  RMP10000  1 paket  28000

[10000 rows x 3 columns]

In [17]:
df[df.total_sales > 150000][['order_id','unit','price']]

      order_id     unit  price
123   RMP00124  1 paket  32000
145   RMP00146  1 paket  28000
364   RMP00365  1 paket  32000
617   RMP00618  1 paket  32000
626   RMP00627  1 paket  28000
941   RMP00942  1 paket  32000
1116  RMP01117  1 paket  28000
1300  RMP01301  1 paket  25000
1384  RMP01385  1 paket  32000
2024  RMP02025  1 paket  32000
2227  RMP02228  1 paket  25000
2253  RMP02254  1 paket  28000
2301  RMP02302  1 paket  32000
2685  RMP02686  1 paket  28000
2713  RMP02714  1 paket  28000
2727  RMP02728  1 paket  32000
2943  RMP02944  1 paket  28000
3303  RMP03304  1 paket  32000
3572  RMP03573  1 paket  28000
3663  RMP03664  1 paket  28000
4585  RMP04586  1 paket  28000
4598  RMP04599  1 paket  32000
4779  RMP04780  1 paket  32000
4898  RMP04899  1 paket  32000
5348  RMP05349  1 paket  32000
5382  RMP05383  1 paket  32000
5945  RMP05946  1 paket  32000
6058  RMP06059  1 paket  32000
6170  RMP06171  1 paket  28000
6493  RMP06494  1 paket  28000
6846  RMP06847  1 paket  32000
6974  RMP06975  1 paket  32000
7121  RMP07122  1 paket  32000
7188  RMP07189  1 paket  32000
8076  RMP08077  1 paket  32000
8341  RMP08342  1 paket  32000
8427  RMP08428  1 paket  28000
8623  RMP08624  1 paket  25000
9280  RMP09281  1 paket  28000

2.3 Filtering Majemuk: .isin() dan .between()
Dua fungsi ini bikin filtering yang tadinya ribet (banyak | dan &) jadi lebih ringkas.

.isin() buat cek apakah nilai ada di dalam sebuah list:

In [ ]:
#isin merupakan fungsi filtering yang lebih ringkas menggunakan string list

search_cat = ["Paket Bumbu Instan", "Rempah Kering & Bumbu Dapur"]
df[df['category'].isin(["Paket Bumbu Instan", "Rempah Kering & Bumbu Dapur"])]

,sales_date,order_id,customer_name,customer_address,product_name,category,unit,price,quantity,order_type,distance_km,discount,total,shipping_fee,total_sales,status
0,2025-07-17,RMP00001,Customer_1198,"Kecamatan Cicalengka, Kabupaten Bandung",Bunga Lawang (Pekak),Rempah Kering & Bumbu Dapur,50 gr,9000,1,Beli di Toko,0.0,0.00,9000,0,9000,completed
2,2025-11-15,RMP00003,Customer_575,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Gule Sapi,Paket Bumbu Instan,1 paket,15000,2,Diantar (Aplikasi Toko),14.2,0.00,30000,25000,55000,completed
3,2025-06-06,RMP00004,Customer_1394,"Kecamatan Cisarua, Kabupaten Bandung Barat",Paket Bumbu Soto Betawi,Paket Bumbu Instan,1 paket,22000,1,Beli di Toko,0.0,0.00,22000,0,22000,completed
4,2025-12-13,RMP00005,Customer_1382,"Kecamatan Sukajadi, Kota Bandung",Paket Bumbu Woku Manado,Paket Bumbu Instan,1 paket,20000,1,Diantar (Aplikasi Toko),1.5,0.00,20000,0,20000,completed
5,2025-09-09,RMP00006,Customer_1979,"Kecamatan Cibiru, Kota Bandung",Paket Bumbu Kerupuk Sambal,Paket Bumbu Instan,1 paket,28000,2,Diantar (Aplikasi Toko),7.8,0.05,53200,13000,66200,completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2025-05-19,RMP09996,Customer_427,"Kecamatan Cicalengka, Kabupaten Bandung",Paket Bumbu Nasi Goreng,Paket Bumbu Instan,1 paket,17000,2,Beli di Toko,0.0,0.10,30600,0,30600,completed
9996,2025-04-12,RMP09997,Customer_1357,"Kecamatan Banjaran, Kabupaten Bandung",Bunga Lawang (Pekak),Rempah Kering & Bumbu Dapur,50 gr,9000,3,Diantar (Aplikasi Toko),20.4,0.00,27000,32000,59000,cancelled
9997,2025-01-02,RMP09998,Customer_3176,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Tongseng,Paket Bumbu Instan,1 paket,14000,1,Diantar (Aplikasi Toko),10.9,0.00,14000,18000,32000,completed
9998,2025-12-26,RMP09999,Customer_730,"Kecamatan Cileunyi, Kabupaten Bandung",Paket Bumbu Rica-Rica,Paket Bumbu Instan,1 paket,32000,1,Diantar (Aplikasi Toko),12.5,0.00,32000,25000,57000,completed
9999,2025-10-25,RMP10000,Customer_1425,"Kecamatan Astanaanyar, Kota Bandung",Paket Bumbu Pecel,Paket Bumbu Instan,1 paket,28000,2,Beli di Toko,0.0,0.00,56000,0,56000,completed

In [20]:
search_cat = ["Paket Bumbu Instan", "Rempah Kering & Bumbu Dapur"]
df[df['category'].isin(search_cat)]

,sales_date,order_id,customer_name,customer_address,product_name,category,unit,price,quantity,order_type,distance_km,discount,total,shipping_fee,total_sales,status
0,2025-07-17,RMP00001,Customer_1198,"Kecamatan Cicalengka, Kabupaten Bandung",Bunga Lawang (Pekak),Rempah Kering & Bumbu Dapur,50 gr,9000,1,Beli di Toko,0.0,0.00,9000,0,9000,completed
2,2025-11-15,RMP00003,Customer_575,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Gule Sapi,Paket Bumbu Instan,1 paket,15000,2,Diantar (Aplikasi Toko),14.2,0.00,30000,25000,55000,completed
3,2025-06-06,RMP00004,Customer_1394,"Kecamatan Cisarua, Kabupaten Bandung Barat",Paket Bumbu Soto Betawi,Paket Bumbu Instan,1 paket,22000,1,Beli di Toko,0.0,0.00,22000,0,22000,completed
4,2025-12-13,RMP00005,Customer_1382,"Kecamatan Sukajadi, Kota Bandung",Paket Bumbu Woku Manado,Paket Bumbu Instan,1 paket,20000,1,Diantar (Aplikasi Toko),1.5,0.00,20000,0,20000,completed
5,2025-09-09,RMP00006,Customer_1979,"Kecamatan Cibiru, Kota Bandung",Paket Bumbu Kerupuk Sambal,Paket Bumbu Instan,1 paket,28000,2,Diantar (Aplikasi Toko),7.8,0.05,53200,13000,66200,completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2025-05-19,RMP09996,Customer_427,"Kecamatan Cicalengka, Kabupaten Bandung",Paket Bumbu Nasi Goreng,Paket Bumbu Instan,1 paket,17000,2,Beli di Toko,0.0,0.10,30600,0,30600,completed
9996,2025-04-12,RMP09997,Customer_1357,"Kecamatan Banjaran, Kabupaten Bandung",Bunga Lawang (Pekak),Rempah Kering & Bumbu Dapur,50 gr,9000,3,Diantar (Aplikasi Toko),20.4,0.00,27000,32000,59000,cancelled
9997,2025-01-02,RMP09998,Customer_3176,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Tongseng,Paket Bumbu Instan,1 paket,14000,1,Diantar (Aplikasi Toko),10.9,0.00,14000,18000,32000,completed
9998,2025-12-26,RMP09999,Customer_730,"Kecamatan Cileunyi, Kabupaten Bandung",Paket Bumbu Rica-Rica,Paket Bumbu Instan,1 paket,32000,1,Diantar (Aplikasi Toko),12.5,0.00,32000,25000,57000,completed
9999,2025-10-25,RMP10000,Customer_1425,"Kecamatan Astanaanyar, Kota Bandung",Paket Bumbu Pecel,Paket Bumbu Instan,1 paket,28000,2,Beli di Toko,0.0,0.00,56000,0,56000,completed

In [21]:
df[(df.category == "Paket Bumbu Instan") | (df.category == "Rempah Kering & Bumbu Dapur")]

,sales_date,order_id,customer_name,customer_address,product_name,category,unit,price,quantity,order_type,distance_km,discount,total,shipping_fee,total_sales,status
0,2025-07-17,RMP00001,Customer_1198,"Kecamatan Cicalengka, Kabupaten Bandung",Bunga Lawang (Pekak),Rempah Kering & Bumbu Dapur,50 gr,9000,1,Beli di Toko,0.0,0.00,9000,0,9000,completed
2,2025-11-15,RMP00003,Customer_575,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Gule Sapi,Paket Bumbu Instan,1 paket,15000,2,Diantar (Aplikasi Toko),14.2,0.00,30000,25000,55000,completed
3,2025-06-06,RMP00004,Customer_1394,"Kecamatan Cisarua, Kabupaten Bandung Barat",Paket Bumbu Soto Betawi,Paket Bumbu Instan,1 paket,22000,1,Beli di Toko,0.0,0.00,22000,0,22000,completed
4,2025-12-13,RMP00005,Customer_1382,"Kecamatan Sukajadi, Kota Bandung",Paket Bumbu Woku Manado,Paket Bumbu Instan,1 paket,20000,1,Diantar (Aplikasi Toko),1.5,0.00,20000,0,20000,completed
5,2025-09-09,RMP00006,Customer_1979,"Kecamatan Cibiru, Kota Bandung",Paket Bumbu Kerupuk Sambal,Paket Bumbu Instan,1 paket,28000,2,Diantar (Aplikasi Toko),7.8,0.05,53200,13000,66200,completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2025-05-19,RMP09996,Customer_427,"Kecamatan Cicalengka, Kabupaten Bandung",Paket Bumbu Nasi Goreng,Paket Bumbu Instan,1 paket,17000,2,Beli di Toko,0.0,0.10,30600,0,30600,completed
9996,2025-04-12,RMP09997,Customer_1357,"Kecamatan Banjaran, Kabupaten Bandung",Bunga Lawang (Pekak),Rempah Kering & Bumbu Dapur,50 gr,9000,3,Diantar (Aplikasi Toko),20.4,0.00,27000,32000,59000,cancelled
9997,2025-01-02,RMP09998,Customer_3176,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Tongseng,Paket Bumbu Instan,1 paket,14000,1,Diantar (Aplikasi Toko),10.9,0.00,14000,18000,32000,completed
9998,2025-12-26,RMP09999,Customer_730,"Kecamatan Cileunyi, Kabupaten Bandung",Paket Bumbu Rica-Rica,Paket Bumbu Instan,1 paket,32000,1,Diantar (Aplikasi Toko),12.5,0.00,32000,25000,57000,completed
9999,2025-10-25,RMP10000,Customer_1425,"Kecamatan Astanaanyar, Kota Bandung",Paket Bumbu Pecel,Paket Bumbu Instan,1 paket,28000,2,Beli di Toko,0.0,0.00,56000,0,56000,completed

In [22]:
search_cat = ["Paket Bumbu Instan", "Rempah Kering & Bumbu Dapur"]
hasil_isin = df[df['category'].isin(search_cat)]

print("Jumlah transaksi:", len(hasil_isin))

Jumlah transaksi: 7998

In [29]:
#between() merupakan fungsi filtering untuk range nilai tertentu

df[df['distance_km'].between(5,15)]

,sales_date,order_id,customer_name,customer_address,product_name,category,unit,price,quantity,order_type,distance_km,discount,total,shipping_fee,total_sales,status
2,2025-11-15,RMP00003,Customer_575,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Gule Sapi,Paket Bumbu Instan,1 paket,15000,2,Diantar (Aplikasi Toko),14.2,0.00,30000,25000,55000,completed
5,2025-09-09,RMP00006,Customer_1979,"Kecamatan Cibiru, Kota Bandung",Paket Bumbu Kerupuk Sambal,Paket Bumbu Instan,1 paket,28000,2,Diantar (Aplikasi Toko),7.8,0.05,53200,13000,66200,completed
14,2025-12-30,RMP00015,Customer_3247,"Kecamatan Cimahi Tengah, Kota Cimahi",Merica Hitam,Rempah Kering & Bumbu Dapur,100 gr,13000,1,Diantar (Aplikasi Toko),7.1,0.00,13000,13000,26000,completed
15,2025-07-18,RMP00016,Customer_379,"Kecamatan Lembang, Kabupaten Bandung Barat",Paket Bumbu Dasar Merah,Paket Bumbu Instan,1 paket,20000,1,Diantar (Aplikasi Toko),14.1,0.05,19000,25000,44000,completed
16,2025-11-06,RMP00017,Customer_521,"Kecamatan Gedebage, Kota Bandung",Paket Bumbu Sambal Hijau,Paket Bumbu Instan,1 paket,32000,1,Diantar (Aplikasi Toko),6.9,0.10,28800,13000,41800,completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9991,2025-11-16,RMP09992,Customer_1478,"Kecamatan Cimahi Selatan, Kota Cimahi",Paket Bumbu Gulai Ikan,Paket Bumbu Instan,1 paket,17000,1,Diantar (Aplikasi Toko),9.7,0.00,17000,18000,35000,completed
9992,2025-01-13,RMP09993,Customer_1585,"Kecamatan Lembang, Kabupaten Bandung Barat",Gula Merah,Rempah Kering & Bumbu Dapur,500 gr,13000,1,Diantar (Aplikasi Toko),10.1,0.00,13000,18000,31000,completed
9994,2025-09-17,RMP09995,Customer_3219,"Kecamatan Ngamprah, Kabupaten Bandung Barat",Paket Bumbu Kari Ayam,Paket Bumbu Instan,1 paket,15000,1,Diantar (Aplikasi Toko),14.9,0.00,15000,25000,40000,completed
9997,2025-01-02,RMP09998,Customer_3176,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Tongseng,Paket Bumbu Instan,1 paket,14000,1,Diantar (Aplikasi Toko),10.9,0.00,14000,18000,32000,completed
9998,2025-12-26,RMP09999,Customer_730,"Kecamatan Cileunyi, Kabupaten Bandung",Paket Bumbu Rica-Rica,Paket Bumbu Instan,1 paket,32000,1,Diantar (Aplikasi Toko),12.5,0.00,32000,25000,57000,completed

In [32]:
df[(df["distance_km"] >= 5) & (df["distance_km"] <= 15)]

,sales_date,order_id,customer_name,customer_address,product_name,category,unit,price,quantity,order_type,distance_km,discount,total,shipping_fee,total_sales,status
2,2025-11-15,RMP00003,Customer_575,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Gule Sapi,Paket Bumbu Instan,1 paket,15000,2,Diantar (Aplikasi Toko),14.2,0.00,30000,25000,55000,completed
5,2025-09-09,RMP00006,Customer_1979,"Kecamatan Cibiru, Kota Bandung",Paket Bumbu Kerupuk Sambal,Paket Bumbu Instan,1 paket,28000,2,Diantar (Aplikasi Toko),7.8,0.05,53200,13000,66200,completed
14,2025-12-30,RMP00015,Customer_3247,"Kecamatan Cimahi Tengah, Kota Cimahi",Merica Hitam,Rempah Kering & Bumbu Dapur,100 gr,13000,1,Diantar (Aplikasi Toko),7.1,0.00,13000,13000,26000,completed
15,2025-07-18,RMP00016,Customer_379,"Kecamatan Lembang, Kabupaten Bandung Barat",Paket Bumbu Dasar Merah,Paket Bumbu Instan,1 paket,20000,1,Diantar (Aplikasi Toko),14.1,0.05,19000,25000,44000,completed
16,2025-11-06,RMP00017,Customer_521,"Kecamatan Gedebage, Kota Bandung",Paket Bumbu Sambal Hijau,Paket Bumbu Instan,1 paket,32000,1,Diantar (Aplikasi Toko),6.9,0.10,28800,13000,41800,completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9991,2025-11-16,RMP09992,Customer_1478,"Kecamatan Cimahi Selatan, Kota Cimahi",Paket Bumbu Gulai Ikan,Paket Bumbu Instan,1 paket,17000,1,Diantar (Aplikasi Toko),9.7,0.00,17000,18000,35000,completed
9992,2025-01-13,RMP09993,Customer_1585,"Kecamatan Lembang, Kabupaten Bandung Barat",Gula Merah,Rempah Kering & Bumbu Dapur,500 gr,13000,1,Diantar (Aplikasi Toko),10.1,0.00,13000,18000,31000,completed
9994,2025-09-17,RMP09995,Customer_3219,"Kecamatan Ngamprah, Kabupaten Bandung Barat",Paket Bumbu Kari Ayam,Paket Bumbu Instan,1 paket,15000,1,Diantar (Aplikasi Toko),14.9,0.00,15000,25000,40000,completed
9997,2025-01-02,RMP09998,Customer_3176,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Tongseng,Paket Bumbu Instan,1 paket,14000,1,Diantar (Aplikasi Toko),10.9,0.00,14000,18000,32000,completed
9998,2025-12-26,RMP09999,Customer_730,"Kecamatan Cileunyi, Kabupaten Bandung",Paket Bumbu Rica-Rica,Paket Bumbu Instan,1 paket,32000,1,Diantar (Aplikasi Toko),12.5,0.00,32000,25000,57000,completed

In [31]:
mid_dist = df[df['distance_km'].between(5,15)]

print("Jarak menengah(5-15 km) transaksi sebanyak:", len(mid_dist))

Jarak menengah(5-15 km) transaksi sebanyak: 1961

2.4 .apply() + lambda: Bikin Kolom Baru dari Logika Custom
.apply() dipakai buat menjalankan sebuah fungsi ke setiap nilai di suatu kolom. Kita bisa pakai function biasa (def), atau kalau logikanya simpel dan cuma dipakai sekali, bisa pakai lambda (function tanpa nama, ditulis dalam satu baris).

In [ ]:
#apply() + lambda function membuat kolom baru
#apply menerapkan fungsi ke setiap baris/kolom, 
#bisa menggunakan def atau lambda function jika logika sederhana

def class_trans(nilai):
    if nilai < 20000:
        return "Kecil",
    if nilai <= 60000:
        return "Sedang",
    else:
        return "Besar"
    
df["segment_transaksi"] = df["total_sales"].apply(class_trans)

df["ada_diskon"] = df["discount"].apply(lambda x: "Ya" if x > 0 else "Tidak")

df[["total_sales","segment_transaksi","discount","ada_diskon"]].head(10)

    total_sales segment_transaksi  discount ada_diskon
0          9000          (Kecil,)      0.00      Tidak
2         55000         (Sedang,)      0.00      Tidak
3         22000         (Sedang,)      0.00      Tidak
4         20000         (Sedang,)      0.00      Tidak
5         66200             Besar      0.05         Ya
8          6000          (Kecil,)      0.00      Tidak
9         88000             Besar      0.00      Tidak
10        14000          (Kecil,)      0.00      Tidak
11        14000          (Kecil,)      0.00      Tidak
14        26000         (Sedang,)      0.00      Tidak

In [36]:
df['discount'].apply(lambda x:"Ya" if x > 0 else "Tidak").head()

0    Tidak
2    Tidak
3    Tidak
4    Tidak
5       Ya
Name: discount, dtype: str

In [37]:
def class_trans(nilai):
    if nilai < 20000:
        return "Kecil"
    if nilai <= 60000:
        return "Sedang"
    return "Besar"

In [40]:
df['segment_transaksi'] = df['total_sales'].apply(class_trans)
df.head(10)

,sales_date,order_id,customer_name,customer_address,product_name,category,unit,price,quantity,order_type,distance_km,discount,total,shipping_fee,total_sales,status,segment_transaksi,ada_diskon
0,2025-07-17,RMP00001,Customer_1198,"Kecamatan Cicalengka, Kabupaten Bandung",Bunga Lawang (Pekak),Rempah Kering & Bumbu Dapur,50 gr,9000,1,Beli di Toko,0.0,0.00,9000,0,9000,completed,Kecil,Tidak
2,2025-11-15,RMP00003,Customer_575,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Gule Sapi,Paket Bumbu Instan,1 paket,15000,2,Diantar (Aplikasi Toko),14.2,0.00,30000,25000,55000,completed,Sedang,Tidak
3,2025-06-06,RMP00004,Customer_1394,"Kecamatan Cisarua, Kabupaten Bandung Barat",Paket Bumbu Soto Betawi,Paket Bumbu Instan,1 paket,22000,1,Beli di Toko,0.0,0.00,22000,0,22000,completed,Sedang,Tidak
4,2025-12-13,RMP00005,Customer_1382,"Kecamatan Sukajadi, Kota Bandung",Paket Bumbu Woku Manado,Paket Bumbu Instan,1 paket,20000,1,Diantar (Aplikasi Toko),1.5,0.00,20000,0,20000,completed,Sedang,Tidak
5,2025-09-09,RMP00006,Customer_1979,"Kecamatan Cibiru, Kota Bandung",Paket Bumbu Kerupuk Sambal,Paket Bumbu Instan,1 paket,28000,2,Diantar (Aplikasi Toko),7.8,0.05,53200,13000,66200,completed,Besar,Ya
8,2025-09-03,RMP00009,Customer_1197,"Kecamatan Bandung Wetan, Kota Bandung",Asam Jawa,Rempah Kering & Bumbu Dapur,100 gr,6000,1,Diantar (Aplikasi Toko),1.7,0.00,6000,0,6000,completed,Kecil,Tidak
9,2025-10-25,RMP00010,Customer_1738,"Kecamatan Cicalengka, Kabupaten Bandung",Paket Bumbu Semur Daging,Paket Bumbu Instan,1 paket,28000,2,Diantar (Aplikasi Toko),22.7,0.00,56000,32000,88000,cancelled,Besar,Tidak
10,2025-01-06,RMP00011,Customer_3907,"Kecamatan Antapani, Kota Bandung",Paket Bumbu Ayam Rica,Paket Bumbu Instan,1 paket,14000,1,Beli di Toko,0.0,0.00,14000,0,14000,completed,Kecil,Tidak
11,2025-10-27,RMP00012,Customer_1032,"Kecamatan Ciwidey, Kabupaten Bandung",Paket Bumbu Ayam Rica,Paket Bumbu Instan,1 paket,14000,1,Beli di Toko,0.0,0.00,14000,0,14000,completed,Kecil,Tidak
14,2025-12-30,RMP00015,Customer_3247,"Kecamatan Cimahi Tengah, Kota Cimahi",Merica Hitam,Rempah Kering & Bumbu Dapur,100 gr,13000,1,Diantar (Aplikasi Toko),7.1,0.00,13000,13000,26000,completed,Sedang,Tidak

In [41]:
class_trans(150000)

'Besar'

3. Data Cleaning: Outlier & String Methods
3.1 Deteksi Outlier Pakai Metode IQR
Selain cek missing value dan duplikat, cleaning yang lebih dalam juga perlu cek outlier, yaitu nilai yang jauh banget beda dari kebanyakan data, bisa jadi kesalahan input, bisa juga transaksi yang memang wajar tapi ekstrem.

Salah satu metode yang umum dipakai adalah IQR (Interquartile Range): hitung Q1 (persentil 25) dan Q3 (persentil 75), lalu nilai di luar rentang Q1 - 1.5×IQR sampai Q3 + 1.5×IQR dianggap outlier.

In [44]:
finish_trans = df[df["status"]=="completed"].copy()

Q1 = finish_trans["total_sales"].quantile(0.25)
Q3 = finish_trans["total_sales"].quantile(0.75)
IQR= Q3-Q1
batas_bawah = Q1 - 1.5*IQR
batas_atas = Q3 + 1.5*IQR

print(f"Q1: {Q1:,.0f} | Q3: {Q3:,.0f} | IQR: {IQR:,.0f}")
print(f"Batas atas outlier: {batas_atas:,.0f}")

outlier = finish_trans[finish_trans["total_sales"] > batas_atas]
print("Jumlah transaksi outlier:", len(outlier))
print(f"Total pendapatan dari transaksi outlier: Rp {outlier['total_sales'].sum():,.0f}".replace(",", "."))

Q1: 22,000 | Q3: 57,000 | IQR: 35,000
Batas atas outlier: 109,500
Jumlah transaksi outlier: 267
Total pendapatan dari transaksi outlier: Rp 34.444.950

In [45]:
finish_trans[finish_trans["total_sales"] < batas_bawah]

Empty DataFrame
Columns: [sales_date, order_id, customer_name, customer_address, product_name, category, unit, price, quantity, order_type, distance_km, discount, total, shipping_fee, total_sales, status, segment_transaksi, ada_diskon]
Index: []

Penting: outlier itu nggak otomatis berarti "data salah". Di kasus kita ini kemungkinan besar itu transaksi pembelian dalam jumlah besar yang memang valid (misalnya buat acara atau reseller), bukan kesalahan input. Makanya, ketemu outlier itu bukan otomatis dihapus, tapi jadi bahan buat digali lebih lanjut.

3.2 String Methods Lanjutan
Kita udah pernah pakai str.extract() buat ambil kecamatan. Sekarang kenalan sama dua fungsi string lain yang sering kepake.

.str.contains() buat cek apakah suatu teks mengandung kata tertentu:

In [56]:
cust_bandung = df[df["customer_address"].str.contains("Bandung")]
cust_cimahi = df[df["customer_address"].str.contains("Cimahi")]

print("Jumlah transaksi dari Bandung:", len(cust_bandung))
print("Jumlah transaksi dari Cimahi:", len(cust_cimahi))

Jumlah transaksi dari Bandung: 7197
Jumlah transaksi dari Cimahi: 801

In [58]:
df[df["customer_address"].str.contains("Bandung")]

,sales_date,order_id,customer_name,customer_address,product_name,category,unit,price,quantity,order_type,distance_km,discount,total,shipping_fee,total_sales,status,segment_transaksi,ada_diskon
0,2025-07-17,RMP00001,Customer_1198,"Kecamatan Cicalengka, Kabupaten Bandung",Bunga Lawang (Pekak),Rempah Kering & Bumbu Dapur,50 gr,9000,1,Beli di Toko,0.0,0.00,9000,0,9000,completed,Kecil,Tidak
2,2025-11-15,RMP00003,Customer_575,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Gule Sapi,Paket Bumbu Instan,1 paket,15000,2,Diantar (Aplikasi Toko),14.2,0.00,30000,25000,55000,completed,Sedang,Tidak
3,2025-06-06,RMP00004,Customer_1394,"Kecamatan Cisarua, Kabupaten Bandung Barat",Paket Bumbu Soto Betawi,Paket Bumbu Instan,1 paket,22000,1,Beli di Toko,0.0,0.00,22000,0,22000,completed,Sedang,Tidak
4,2025-12-13,RMP00005,Customer_1382,"Kecamatan Sukajadi, Kota Bandung",Paket Bumbu Woku Manado,Paket Bumbu Instan,1 paket,20000,1,Diantar (Aplikasi Toko),1.5,0.00,20000,0,20000,completed,Sedang,Tidak
5,2025-09-09,RMP00006,Customer_1979,"Kecamatan Cibiru, Kota Bandung",Paket Bumbu Kerupuk Sambal,Paket Bumbu Instan,1 paket,28000,2,Diantar (Aplikasi Toko),7.8,0.05,53200,13000,66200,completed,Besar,Ya
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2025-05-19,RMP09996,Customer_427,"Kecamatan Cicalengka, Kabupaten Bandung",Paket Bumbu Nasi Goreng,Paket Bumbu Instan,1 paket,17000,2,Beli di Toko,0.0,0.10,30600,0,30600,completed,Sedang,Ya
9996,2025-04-12,RMP09997,Customer_1357,"Kecamatan Banjaran, Kabupaten Bandung",Bunga Lawang (Pekak),Rempah Kering & Bumbu Dapur,50 gr,9000,3,Diantar (Aplikasi Toko),20.4,0.00,27000,32000,59000,cancelled,Sedang,Tidak
9997,2025-01-02,RMP09998,Customer_3176,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Tongseng,Paket Bumbu Instan,1 paket,14000,1,Diantar (Aplikasi Toko),10.9,0.00,14000,18000,32000,completed,Sedang,Tidak
9998,2025-12-26,RMP09999,Customer_730,"Kecamatan Cileunyi, Kabupaten Bandung",Paket Bumbu Rica-Rica,Paket Bumbu Instan,1 paket,32000,1,Diantar (Aplikasi Toko),12.5,0.00,32000,25000,57000,completed,Sedang,Tidak
9999,2025-10-25,RMP10000,Customer_1425,"Kecamatan Astanaanyar, Kota Bandung",Paket Bumbu Pecel,Paket Bumbu Instan,1 paket,28000,2,Beli di Toko,0.0,0.00,56000,0,56000,completed,Sedang,Tidak

.str.split() buat memecah teks jadi beberapa bagian berdasarkan pemisah tertentu (mirip split() di Python biasa, tapi versi pandas, bisa langsung diterapkan ke seluruh kolom):

In [59]:
alamat_terpisah = df["customer_address"].str.split(",", expand=True)
alamat_terpisah.columns = ["kecamatan_raw", "kota_kabupaten_raw"]

df["kecamatan"] = alamat_terpisah["kecamatan_raw"].str.replace("Kecamatan","", regex=False).str.strip()
df["kota_kabupaten"] = alamat_terpisah["kota_kabupaten_raw"].str.strip()

df[["customer_address","kecamatan","kota_kabupaten"]].head()

,customer_address,kecamatan,kota_kabupaten
0,"Kecamatan Cicalengka, Kabupaten Bandung",Cicalengka,Kabupaten Bandung
2,"Kecamatan Padalarang, Kabupaten Bandung Barat",Padalarang,Kabupaten Bandung Barat
3,"Kecamatan Cisarua, Kabupaten Bandung Barat",Cisarua,Kabupaten Bandung Barat
4,"Kecamatan Sukajadi, Kota Bandung",Sukajadi,Kota Bandung
5,"Kecamatan Cibiru, Kota Bandung",Cibiru,Kota Bandung

In [60]:
alamat_terpisah = df["customer_address"].str.split(",", expand = True)
alamat_terpisah.columns = ["kecamatan_raw", "kota_kabupaten_raw"]

alamat_terpisah['kecamatan_raw'].str.replace("Kecamatan ", "").str.strip()

0        Cicalengka
2        Padalarang
3           Cisarua
4          Sukajadi
5            Cibiru
           ...
9995     Cicalengka
9996       Banjaran
9997     Padalarang
9998       Cileunyi
9999    Astanaanyar
Name: kecamatan_raw, Length: 7998, dtype: str

4. GroupBy: Agregasi Ganda, Transform, dan Rank
4.1 .agg() dengan Banyak Fungsi Sekaligus
Kemarin kita cuma pakai satu fungsi agregasi tiap kali (.sum() atau .mean() sendiri-sendiri). Sekarang kita bisa hitung beberapa sekaligus pakai .agg().

In [61]:
transaksi_selesai = df[df["status"] == "completed"].copy()

ringkasan_kategori = transaksi_selesai.groupby("category")["total_sales"].agg(["sum", "mean", "count"])
ringkasan_kategori.columns = ["total_pendapatan", "rata_rata_pendapatan", "jumlah_transaksi"]
ringkasan_kategori.round(0)

,total_pendapatan,rata_rata_pendapatan,jumlah_transaksi
category,,,
Paket Bumbu Instan,264921050,48860.0,5422
Rempah Kering & Bumbu Dapur,47567075,26456.0,1798

In [62]:
ringkasan_kategori = transaksi_selesai.groupby("category")['total_sales'].agg(['sum','mean','count'])
ringkasan_kategori.columns = ['total_pendapatan','rata_rata_pendapatan','jumlah_transaksi']
ringkasan_kategori.reset_index()

,category,total_pendapatan,rata_rata_pendapatan,jumlah_transaksi
0,Paket Bumbu Instan,264921050,48860.392844,5422
1,Rempah Kering & Bumbu Dapur,47567075,26455.547831,1798

4.2 .transform(): Bandingkan Tiap Baris dengan Rata-Rata Grupnya
groupby().sum() atau .mean() biasa itu hasilnya meringkas data (dari 9000 baris jadi cuma 3 baris kategori). Tapi kadang kita mau tetap punya 9000 baris itu, cuma nambahin kolom "rata-rata kategorinya berapa" di tiap baris. Nah, itu gunanya .transform().

In [63]:
display(transaksi_selesai.groupby("category")["total_sales"].mean())

transaksi_selesai["rata2_kategori"] = transaksi_selesai.groupby("category")["total_sales"].transform("mean")
transaksi_selesai

category
Paket Bumbu Instan             48860.392844
Rempah Kering & Bumbu Dapur    26455.547831
Name: total_sales, dtype: float64

,sales_date,order_id,customer_name,customer_address,product_name,category,unit,price,quantity,order_type,...,discount,total,shipping_fee,total_sales,status,segment_transaksi,ada_diskon,kecamatan,kota_kabupaten,rata2_kategori
0,2025-07-17,RMP00001,Customer_1198,"Kecamatan Cicalengka, Kabupaten Bandung",Bunga Lawang (Pekak),Rempah Kering & Bumbu Dapur,50 gr,9000,1,Beli di Toko,...,0.00,9000,0,9000,completed,Kecil,Tidak,Cicalengka,Kabupaten Bandung,26455.547831
2,2025-11-15,RMP00003,Customer_575,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Gule Sapi,Paket Bumbu Instan,1 paket,15000,2,Diantar (Aplikasi Toko),...,0.00,30000,25000,55000,completed,Sedang,Tidak,Padalarang,Kabupaten Bandung Barat,48860.392844
3,2025-06-06,RMP00004,Customer_1394,"Kecamatan Cisarua, Kabupaten Bandung Barat",Paket Bumbu Soto Betawi,Paket Bumbu Instan,1 paket,22000,1,Beli di Toko,...,0.00,22000,0,22000,completed,Sedang,Tidak,Cisarua,Kabupaten Bandung Barat,48860.392844
4,2025-12-13,RMP00005,Customer_1382,"Kecamatan Sukajadi, Kota Bandung",Paket Bumbu Woku Manado,Paket Bumbu Instan,1 paket,20000,1,Diantar (Aplikasi Toko),...,0.00,20000,0,20000,completed,Sedang,Tidak,Sukajadi,Kota Bandung,48860.392844
5,2025-09-09,RMP00006,Customer_1979,"Kecamatan Cibiru, Kota Bandung",Paket Bumbu Kerupuk Sambal,Paket Bumbu Instan,1 paket,28000,2,Diantar (Aplikasi Toko),...,0.05,53200,13000,66200,completed,Besar,Ya,Cibiru,Kota Bandung,48860.392844
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,2025-09-17,RMP09995,Customer_3219,"Kecamatan Ngamprah, Kabupaten Bandung Barat",Paket Bumbu Kari Ayam,Paket Bumbu Instan,1 paket,15000,1,Diantar (Aplikasi Toko),...,0.00,15000,25000,40000,completed,Sedang,Tidak,Ngamprah,Kabupaten Bandung Barat,48860.392844
9995,2025-05-19,RMP09996,Customer_427,"Kecamatan Cicalengka, Kabupaten Bandung",Paket Bumbu Nasi Goreng,Paket Bumbu Instan,1 paket,17000,2,Beli di Toko,...,0.10,30600,0,30600,completed,Sedang,Ya,Cicalengka,Kabupaten Bandung,48860.392844
9997,2025-01-02,RMP09998,Customer_3176,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Tongseng,Paket Bumbu Instan,1 paket,14000,1,Diantar (Aplikasi Toko),...,0.00,14000,18000,32000,completed,Sedang,Tidak,Padalarang,Kabupaten Bandung Barat,48860.392844
9998,2025-12-26,RMP09999,Customer_730,"Kecamatan Cileunyi, Kabupaten Bandung",Paket Bumbu Rica-Rica,Paket Bumbu Instan,1 paket,32000,1,Diantar (Aplikasi Toko),...,0.00,32000,25000,57000,completed,Sedang,Tidak,Cileunyi,Kabupaten Bandung,48860.392844
9999,2025-10-25,RMP10000,Customer_1425,"Kecamatan Astanaanyar, Kota Bandung",Paket Bumbu Pecel,Paket Bumbu Instan,1 paket,28000,2,Beli di Toko,...,0.00,56000,0,56000,completed,Sedang,Tidak,Astanaanyar,Kota Bandung,48860.392844

In [64]:
transaksi_selesai["rata2_kategori"] = (
    transaksi_selesai.groupby("category")["total_sales"].transform("mean")
)
transaksi_selesai["selisih_dari_rata2"] = (
    transaksi_selesai["total_sales"] - transaksi_selesai["rata2_kategori"]
)

transaksi_selesai[["product_name", "category", "total_sales", "rata2_kategori", "selisih_dari_rata2"]].head()

,product_name,category,total_sales,rata2_kategori,selisih_dari_rata2
0,Bunga Lawang (Pekak),Rempah Kering & Bumbu Dapur,9000,26455.547831,-17455.547831
2,Paket Bumbu Gule Sapi,Paket Bumbu Instan,55000,48860.392844,6139.607156
3,Paket Bumbu Soto Betawi,Paket Bumbu Instan,22000,48860.392844,-26860.392844
4,Paket Bumbu Woku Manado,Paket Bumbu Instan,20000,48860.392844,-28860.392844
5,Paket Bumbu Kerupuk Sambal,Paket Bumbu Instan,66200,48860.392844,17339.607156

Kolom selisih_dari_rata2 ini berguna banget buat cari transaksi yang jauh di atas atau di bawah kebiasaan kategorinya, kita pakai ini di case study nanti.

4.3 .rank(): Bikin Peringkat di Dalam Grup
.rank() dipakai buat kasih peringkat, dan kalau digabung sama groupby(), kita bisa bikin peringkat di dalam masing-masing grup, bukan peringkat keseluruhan.

In [65]:
transaksi_selesai.groupby(["category", "product_name"])["total_sales"].sum().reset_index()

                       category             product_name  total_sales
0            Paket Bumbu Instan   Paket Bumbu Asam Padeh      3152700
1            Paket Bumbu Instan   Paket Bumbu Ayam Bakar      4406000
2            Paket Bumbu Instan  Paket Bumbu Ayam Geprek      2901200
3            Paket Bumbu Instan   Paket Bumbu Ayam Kecap      3354750
4            Paket Bumbu Instan    Paket Bumbu Ayam Rica      3637000
..                          ...                      ...          ...
75  Rempah Kering & Bumbu Dapur             Merica Putih      2905200
76  Rempah Kering & Bumbu Dapur                     Pala      3397250
77  Rempah Kering & Bumbu Dapur             Terasi Udang      2357725
78  Rempah Kering & Bumbu Dapur             Vanili Bubuk      1479500
79  Rempah Kering & Bumbu Dapur                    Wijen      2478000

[80 rows x 3 columns]

In [66]:
pendapatan_produk = (transaksi_selesai.groupby(["category","product_name"])["total_sales"].sum().reset_index())

pendapatan_produk["rank_dalam_kategori"]=(pendapatan_produk.groupby("category")["total_sales"].rank(ascending=False, method="min"))

pendapatan_produk.sort_values(["category","rank_dalam_kategori"]).head(10)

,category,product_name,total_sales,rank_dalam_kategori
21,Paket Bumbu Instan,Paket Bumbu Kerupuk Sambal,6937000,1.0
39,Paket Bumbu Instan,Paket Bumbu Rica-Rica,6868000,2.0
41,Paket Bumbu Instan,Paket Bumbu Sambal Hijau,6736400,3.0
34,Paket Bumbu Instan,Paket Bumbu Pindang Ikan,6611000,4.0
22,Paket Bumbu Instan,Paket Bumbu Ketupat Sayur,6594800,5.0
10,Paket Bumbu Instan,Paket Bumbu Coto Makassar,6352200,6.0
57,Paket Bumbu Instan,Paket Bumbu Tumis Kangkung,6107750,7.0
46,Paket Bumbu Instan,Paket Bumbu Sayur Asem,5999800,8.0
28,Paket Bumbu Instan,Paket Bumbu Nasi Uduk,5962750,9.0
48,Paket Bumbu Instan,Paket Bumbu Semur Daging,5935600,10.0

5. Case Study: Laporan Detail buat Teh Rina
Sekarang, gabungin semua teknik baru yang udah kamu pelajari buat jawab pertanyaan-pertanyaan Teh Rina yang lebih spesifik.

Pertanyaan 1: Produk apa yang jadi juara pendapatan DI MASING-MASING kategori?
Petunjuk: pakai hasil rank_dalam_kategori yang udah kita bikin, ambil yang rank-nya 1.

In [ ]:
# Juara pendapatan pada tiap kategori
juara_pendapatan = (
    pendapatan_produk[pendapatan_produk["rank_dalam_kategori"] == 1]
    .sort_values("category")
)

display(juara_pendapatan)

,category,product_name,total_sales,rank_dalam_kategori
21,Paket Bumbu Instan,Paket Bumbu Kerupuk Sambal,6937000,1.0
65,Rempah Kering & Bumbu Dapur,Gula Aren,4306800,1.0

Pertanyaan 2: Seberapa besar kontribusi transaksi "outlier" (pembelian besar) terhadap total pendapatan toko?

In [68]:
# Hitung kontribusi pendapatan transaksi outlier
total_pendapatan_toko = transaksi_selesai["total_sales"].sum()
total_pendapatan_outlier = outlier["total_sales"].sum()
kontribusi_outlier = total_pendapatan_outlier / total_pendapatan_toko * 100

print(f"Total pendapatan toko: Rp{total_pendapatan_toko:,.0f}".replace(",", "."))
print(f"Pendapatan dari outlier: Rp{total_pendapatan_outlier:,.0f}".replace(",", "."))
print(f"Kontribusi outlier: {kontribusi_outlier:.2f}%")

Total pendapatan toko: Rp312.488.125
Pendapatan dari outlier: Rp34.444.950
Kontribusi outlier: 11.02%

Pertanyaan 3: Produk apa aja yang paling sering jadi transaksi "besar" (jauh di atas rata-rata kategorinya)?
Petunjuk: urutkan berdasarkan selisih_dari_rata2 dari yang paling besar.

In [ ]:
# Tampilkan 10 transaksi yang paling jauh di atas rata-rata kategorinya
transaksi_besar = (
    transaksi_selesai[["order_id", "product_name", "category", "total_sales",
                    "rata2_kategori", "selisih_dari_rata2"]]
    .sort_values("selisih_dari_rata2", ascending=False)
    .head(10)
)

display(transaksi_besar)

,order_id,product_name,category,total_sales,rata2_kategori,selisih_dari_rata2
2301,RMP02302,Paket Bumbu Sambal Hijau,Paket Bumbu Instan,192000,48860.392844,143139.607156
3303,RMP03304,Paket Bumbu Sambal Hijau,Paket Bumbu Instan,185000,48860.392844,136139.607156
6058,RMP06059,Paket Bumbu Sambal Hijau,Paket Bumbu Instan,178000,48860.392844,129139.607156
941,RMP00942,Paket Bumbu Sambal Hijau,Paket Bumbu Instan,173000,48860.392844,124139.607156
6846,RMP06847,Paket Bumbu Sambal Hijau,Paket Bumbu Instan,173000,48860.392844,124139.607156
6974,RMP06975,Paket Bumbu Coto Makassar,Paket Bumbu Instan,173000,48860.392844,124139.607156
123,RMP00124,Paket Bumbu Sambal Hijau,Paket Bumbu Instan,169000,48860.392844,120139.607156
2227,RMP02228,Paket Bumbu Pindang Ikan,Paket Bumbu Instan,165000,48860.392844,116139.607156
145,RMP00146,Paket Bumbu Pecel,Paket Bumbu Instan,165000,48860.392844,116139.607156
2024,RMP02025,Paket Bumbu Rica-Rica,Paket Bumbu Instan,165000,48860.392844,116139.607156